[platformio]
; 默认编译哪个环境？你可以随时切换
default_envs = emulator
;默认环境为emulator

;2. [env] 公共配置板块（所有环境都会强制继承这里的内容）
[env]
; 强迫编译器深度扫描第三方库之间的依赖关系，彻底解决库与库之间互相找不到的问题
lib_ldf_mode = chain+
build_flags = 
    -Wno-error
    -Wno-unused-command-line-argument
    -D LV_CONF_INCLUDE_SIMPLE
    -D LV_LVGL_H_INCLUDE_SIMPLE   ; 核心：告诉 LVGL 驱动层使用简化的 #include "lvgl.h" 引入
    -I include
    -I src                       ; 🌟 核心补丁：告诉编译器把整个 src 目录也作为头文件搜索区
    -I src/screen/src/ui

build_unflags = 
    -Werror
    -Wno-old-style-declaration

lib_deps = 
    lvgl/lvgl @ ^8.4.0

;esp32硬件配置
[env:esp32-s3-n16r8]
platform = espressif32
board = esp32-s3-devkitc-1
framework = espidf

board_build.sdkconfig_defaults = sdkconfig.defaults
board_build.esp-idf.sdkconfig_path = sdkconfig.esp32-s3-n16r8
board_build.flash_mode = qio
board_upload.flash_size = 16MB
board_build.partitions = default_16MB.csv

upload_speed = 921600
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
build_flags = 
    ${env.build_flags}
    -D ESP_PLATFORM
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D CONFIG_COMPILER_CXX_RTTI=y
;显式启用 C++ 运行时类型信息（RTTI）支持‌，允许代码使用 dynamic_cast 和 typeid 进行运行时类型识别与安全检查

; PC 端电脑模拟器环境 
[env:emulator]
platform = native        ; 原生平台 (Windows/Mac/Linux)
lib_deps =
    ${env.lib_deps}
    lvgl/lv_drivers @ ~8.3.0   ; LVGL 官方提供的 PC 驱动 (包含 SDL)
build_flags =
    ${env.build_flags}
    -D PC_SIMULATOR        ; 定义一个宏，告诉代码现在是模拟器
    -D USE_SDL
    -I "D:/SDL2-2.32.10/x86_64-w64-mingw32/include"
    ; 2. 核心：告诉链接器去哪里找编译好的 SDL2 动态/静态库
    -L "D:/SDL2-2.32.10/x86_64-w64-mingw32/lib"
    ; 核心补丁 2：告诉 SDL2 库不要强行接管 Windows 的 main 函数（防止链接时报 winmain 冲突）
    -D SDL_MAIN_HANDLED
    -lSDL2                 ; 链接 SDL2 库

custom_gcc = D:/MinGW/bin/gcc.exe
custom_gxx = D:/MinGW/bin/g++.exe